trigger:
- '*'

pr:
- '*'

jobs:
- job: SyncBranches
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: echo "Starting branch synchronization"
    displayName: 'Start Message'

  - checkout: self
    persistCredentials: true
    clean: true

  - script: git remote add github https://github.com/kevincorrea10/AdtalemPOC.git
    displayName: 'Add GitHub remote'

  - script: git fetch github
    displayName: 'Fetch changes from GitHub'

  - script: git push github HEAD:$(Build.SourceBranchName)
  displayName: 'Sync changes to GitHub'

  - script: git pull github $(Build.SourceBranchName)
    displayName: 'Sync changes from GitHub'

  # Add additional tasks here based on your needs

  - script: echo "Additional tasks..."
    displayName: 'Additional Tasks'
